### ISSUE TITLE
Clicking on Datasets results in an error

### ISSUE THREAD

**Issue by merrua** [skepticfx/domstorm#32]
To replicate
1. go to http://domstorm.skepticfx.com/datasets
The page loads with the error "Something went wrong
Work in Progress"

Console shows
Failed to load resource: the server responded with a status of 503 (Service Temporarily Unavailable) http://api.splitscan.skepticfx.com/js/loader.js

**Comment by skepticfx** [comment]
Its no more there and removed. Thanks for reporting though.
